version: "3.7"

services:
  db:
    # Switched to mariadb to support arm64 (not supported by mysql:5.7 images)
    # image: mysql:5.7
    image: mariadb:10
    command: --max_allowed_packet=256M --character_set_server=utf8 --collation_server=utf8_general_ci
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=openmrs
    ports:
      - 3306:3306

  python:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - OCL_ENV
      - OCL_ORG
      - SOURCE_ID
      - SQL_FILE
      - FORCE_OLD_MODE
      - USE_GOLD_MAPPINGS
