version: "3.7"

services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=256M --character_set_server=utf8 --collation_server=utf8_general_ci
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=openmrs
    ports:
      - 3306:3306

  python:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - OCL_ENV=${OCL_ENV:-staging}
      - OCL_ORG=${OCL_ORG:-CIEL}
      - SQL_FILE=${SQL_FILE:-openmrs.sql}
      - FORCE_OLD_MODE=${FORCE_OLD_MODE:-0}
